#!/bin/bash

# Exit on any errors
set -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    ip=$(echo "$ip" | sed "s/:/[/g")
    if [ -z "$list" ]; then
        list="$ip]"
    else
        list="$list,$ip]"
    fi
done

ls -ld $OPENSHIFT_WILDFLY_DIR/env >& /tmp/set.txt
echo $list > $OPENSHIFT_WILDFLY_DIR/env/OPENSHIFT_WILDFLY_CLUSTER
